name: Build and Test NRF loop client sample

on:
  workflow_dispatch:

jobs:
  build_nrf_sample:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/locomuco/loop-client-sdk-nrf:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build loop client
      shell: bash
      run: |
        source /opt/ncs/zephyr/zephyr-env.sh
        cd $GITHUB_WORKSPACE/firmware/zephyr/loop-zephyr
        west build -b nrf52840dk_nrf52840 . -p

    - name: Create build tarball
      run: |
        cd $GITHUB_WORKSPACE/firmware/zephyr/loop-zephyr/build/zephyr
        tar czf loop-zephyr-latest.tar.gz zephyr.hex
        pwd
        ls

    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: loop-zephyr-latest.tar.gz
        path: ${{ github.workspace }}/firmware/zephyr/loop-zephyr/build/zephyr/loop-zephyr-latest.tar.gz

  hw_flash_and_test:
    needs: build_nrf_sample
    runs-on: [self-hosted, nrf52840dk]

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Download build tarball
        uses: actions/download-artifact@v3
        with:
          name: loop-zephyr-latest.tar.gz

      - name: Untar
        run: tar xvf loop-zephyr-latest.tar.gz

      - name: Flash and Verify Test Results
        run: |
          nrfjprog --eraseall -f NRF52
          nrfjprog --program zephyr.hex --verify -f NRF52
          nrfjprog --pinresetenable -f NRF52
          nrfjprog --pinreset -f NRF52
          sleep 3