name: "Docs Smoke Test"
on: 
- pull_request

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Setup Sphinx Build Environment
        run: pip install sphinx sphinx_rtd_theme
      - name: Run a script
        run: make html
