name: build-nrf-sample

on:
  workflow_dispatch:

jobs:  
  container:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/locomuco/loop-client-nrf_connectsdk:latest'
      credentials:
         username: ${{ github.ref }}
         password: ${{ secrets.GITHUB_TOKEN }}
      env: 
        actor: ${{ github.actor }}
        testjob: here is value

    steps:
    - name: Blinky Sample Build
      run: |
        cd /workdir/zephyr
        nrfutil toolchain-manager launch /bin/bash -- -c 'west build -b nrf52840dk_nrf52840 samples/basic/blinky'

    - name: Create build tarball
      run: |
        cd /workdir/zephyr
        tar czf nrf52840_blinky-latest.tar.gz build/zephyr/zephyr.hex

    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: nrf52840_blinky-latest.tar.gz
        path: /workdir/zephyr/build/zephyr/nrf52840_blinky-latest.tar.gz

