name: Build and publish esp-idf docker image to ghcr.io

on:
  workflow_dispatch:

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}-esp-idf
          github_token: ${{ secrets.GHCR_TOKEN }}
          dockerfile: "${{ github.workspace }}/tools/esp_idf/docker/Dockerfile"
          context: "${{ github.workspace }}/tools/esp_idf/docker"