name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

# Cancel any in-progress job or run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Setup Sphinx Build Environment
        run: pip install sphinx sphinx_rtd_theme
      - name: Run a script
        run: make html
      - name: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
