name: build-nrf-sample

on: 
  - pull_request

jobs:  
  container:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/locomuco/loop-client-nrf_connectsdk:latest'
      credentials:
         username: ${{ github.ref }}
         password: ${{ secrets.GITHUB_TOKEN }}
      env: 
        actor: ${{ github.actor }}
        testjob: here is value

    steps:
    - name: Sample Build
      run: |
        cd /workdir/zephyr
        nrfutil toolchain-manager launch /bin/bash -- -c 'west build -b nrf52840dk_nrf52840 samples/basic/blinky'

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name:
          nrf52840_blinky-${{ github.sha }}
        path: |
          /workdir/zephyr/build/zephyr/zephyr.elf
          /workdir/zephyr/build/zephyr/zephyr.hex
          /workdir/zephyr/build/zephyr/zephyr.dts
          /workdir/zephyr/build/zephyr/.config


